### ISSUE TITLE
Error executing process > 'FILENAME_PREFIX (1)'

### ISSUE THREAD

**Issue by azk001** [sid-krish/rhometa#49]
Hi,

I gave this command 

nextflow run theta_est.nf --bam /rhometa/bam/bamcopy/1EE.bam --fa nrpan_AL65_AL22.fna

I got this error.

N E X T F L O W  ~  version 22.04.5
Launching `theta_est.nf` [nauseous_jang] DSL2 - revision: 0511ebd9b4
[52/3df501] process > FILENAME_PREFIX (1) [100%] 1 of 1, failed: 1
[-        ] process > FILTER_BAM          -
[-        ] process > SORT_BAM            -
[-        ] process > FREEBAYES           -
[-        ] process > THETA_ESTIMATE      -
Error executing process > 'FILENAME_PREFIX (1)'

Caused by:
  Process requirement exceed available CPUs -- req: 4; avail: 2

Command executed:

  filename_prefix.py 1.bam none

Command exit status:
  -

Command output:
  (empty)

Work dir:
  /scratch/aubaxk001/Rhometa/rhometa/work/52/3df501089f4741d672e8f480eda53a

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

does anyone have any idea how to resolve this?

Thank you.

**Comment by sid-krish** [comment]
Hi, the amount of system resources and environment (docker, conda etc) to be used can be configured in the nextflow.config file. Based on the error message, line 14 in the nextflow.config file needs to be changed from cpus  = 4 -> cpus  = 2.

Thanks. Let me know if this solves the issue.

**Comment by azk001** [comment]
Thank you for your response. 

I have changed the line 14th of the nextflow.config file.
However, I am getting the same error with the high req.


N E X T F L O W  ~  version 22.04.5
Launching `theta_est.nf` [cheesy_avogadro] DSL2 - revision: 0511ebd9b4
[7d/814bdf] process > FILENAME_PREFIX (1) [100%] 1 of 1, failed: 1
[-        ] process > FILTER_BAM          -
[-        ] process > SORT_BAM            -
[-        ] process > FREEBAYES           -
[-        ] process > THETA_ESTIMATE      -
Error executing process > 'FILENAME_PREFIX (1)'

Caused by:
  Process requirement exceed available memory -- req: 16 GB; avail: 4 GB

Command executed:

  filename_prefix.py 1EE.bam none

Command exit status:
  -

Command output:
  (empty)

Work dir:
  /scratch/aubaxk001/Rhometa/rhometa/work/7d/814bdfb812721ef3760db45d993a84

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by sid-krish** [comment]
The amount of system resources to use, as specified in the nextflow.config file, needs to be within what is available on the system. Based on the error message there is 4GB of ram on the system, so the memory option needs to be set to `4.GB` or less.

**Comment by sid-krish** [comment]
@azk001 how did it go?

**Comment by koadman** [comment]
@sid-krish I wonder if it might be better to set the default params in the nextflow config to be minimal, say 1 core and 4GB RAM which nearly any modern computer will have, so that it works "out of the box" for most people? Perhaps there could be an alternate config file in the repo with beefier settings for use with bigger datasets? Really fancy would be some way to autoscale the process resource requests by dataset size but that might be tricky to set up.

**Comment by azk001** [comment]
Thank you for checking over again. We resolved the issue by reinstalling it a few times and it started working. That error could be because of some dependencies did not install properly while installations.
